### ISSUE TITLE
Error opening project file with database reference

### ISSUE THREAD

**Issue by kijato** [openjump-gis/openjump#118]
I need to use data stored in Postgis. I can add the data source to the project, I can see the data in openjump and I can save the project to file. But, I cannot open the project file with the following error:

```
java.lang.Exception: 'C:\tryIt.jmp Projekt fájl betöltése megszakadt class com.vividsolutions.jump.util.java2xml.XML2Java cannot access a member of class com.vividsolutions.jump.datastore.spatialdatabases.SpatialDSLayer with modifiers "private" error.
	at org.openjump.core.ui.plugin.file.open.OpenProjectWizard.open(OpenProjectWizard.java:197)
	at org.openjump.core.ui.plugin.file.open.OpenProjectWizard.open(OpenProjectWizard.java:138)
	at org.openjump.core.ui.plugin.file.open.OpenProjectWizard.run(OpenProjectWizard.java:133)
	at org.openjump.core.ui.plugin.AbstractWizardPlugin.run(AbstractWizardPlugin.java:73)
	at com.vividsolutions.jump.workbench.ui.task.TaskMonitorManager$TaskWrapper.run(TaskMonitorManager.java:151)
Caused by: java.lang.IllegalAccessException: class com.vividsolutions.jump.util.java2xml.XML2Java cannot access a member of class com.vividsolutions.jump.datastore.spatialdatabases.SpatialDSLayer with modifiers "private"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:489)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:208)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:196)
	at com.vividsolutions.jump.util.java2xml.XML2Java.setValueFromTag(XML2Java.java:271)
	at com.vividsolutions.jump.util.java2xml.XML2Java.setValuesFromTags(XML2Java.java:265)
	at com.vividsolutions.jump.util.java2xml.XML2Java.access$100(XML2Java.java:55)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.normalTagSpecFound(XML2Java.java:111)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.tagSpecFound(XML2Java.java:130)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:92)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:247)
	at com.vividsolutions.jump.util.java2xml.XML2Java.setValueFromTag(XML2Java.java:271)
	at com.vividsolutions.jump.util.java2xml.XML2Java.setValuesFromTags(XML2Java.java:265)
	at com.vividsolutions.jump.util.java2xml.XML2Java.access$100(XML2Java.java:55)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.normalTagSpecFound(XML2Java.java:111)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.tagSpecFound(XML2Java.java:130)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:92)
	at com.vividsolutions.jump.util.java2xml.XML2Java.access$000(XML2Java.java:55)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.fillerTagSpecFound(XML2Java.java:105)
	at com.vividsolutions.jump.util.java2xml.XML2Java$1.tagSpecFound(XML2Java.java:128)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:92)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:247)
	at com.vividsolutions.jump.util.java2xml.XML2Java.read(XML2Java.java:78)
	at org.openjump.core.ui.plugin.file.open.OpenProjectWizard.open(OpenProjectWizard.java:157)
	... 4 more
```

How can I solve it...?

**Comment by mukoki** [comment]
Hi Kijato,
I will try to reproduce. Can you please write the version of OpenJUMP you're using

**Comment by mukoki** [comment]
Hi Kijato,

Indeed, the bug has been fix recently
https://github.com/openjump-gis/openjump/commit/0906acbc6b7710896bdbe9882fc98ba1c93c2b4b

You will have to grab a snapshot (https://sourceforge.net/projects/jump-pilot/files/OpenJUMP2_snapshots/), or to wait for the next official release. The good news is there should be one soon :-)

**Comment by kijato** [comment]
Hi Mukoki,

That is a great news, then I must to use the snapsot at now.
May I ask where could I to find more _(up-to-date)_ information if I would like to try the running from source, or I would like to develop some plugin for my works?

Thx,
kijato

**Comment by mukoki** [comment]
Hi Kijato,

Documentation is a bit old, but you'll find useful resources  here : 
http://www.openjump.org/

For example, downloading instruction : 
https://ojwiki.soldin.de/index.php?title=Downloading_OpenJUMP#Source_Code

running it in eclipse : 
https://ojwiki.soldin.de/index.php?title=How_to_run_OpenJUMP_in_Eclipse

making your own plugin
https://ojwiki.soldin.de/index.php?title=How_to_use_and_make_own_Plugins

Some pages still refer to OpenJUMP 1.x version and may contain outdated example 

Michaël

**Comment by kijato** [comment]
Hi,

There is a new syllabus: [Eclipse: Set up OpenJUMP as a Maven project from git sources](https://ojwiki.soldin.de/index.php?title=Eclipse:_Set_up_OpenJUMP_as_a_Maven_project_from_git_sources).

Thx for [edeso](https://github.com/edeso)! ☺️

**Comment by edeso** [comment]
@kijato can we close this issue as solved?

**Comment by kijato** [comment]
Yes and thank you very much again!
The basic problem has already been solved and everything else need to be in a new thread.
