### ISSUE TITLE
Applying a style on an image loaded with the legacy image reader throws exception

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#24]
Steps to reproduce :
Load a tiff image (ex. RGB) with the legacy image reader (open file).
Apply a line style to outline the image border

java.lang.InstantiationException: com.github.jaiimageio.impl.plugins.tiff.TIFFImageReader
	at java.lang.Class.newInstance(Class.java:427)
	at com.vividsolutions.jump.workbench.imagery.ImageryLayerDataset.createFeatureFactory(ImageryLayerDataset.java:236)
	at com.vividsolutions.jump.workbench.imagery.ImageryLayerDataset.attachImage(ImageryLayerDataset.java:117)
	at com.vividsolutions.jump.workbench.imagery.ImageryLayerDataset.attachImage(ImageryLayerDataset.java:106)
	at com.vividsolutions.jump.workbench.imagery.ImageryLayerDataset.referencedImage(ImageryLayerDataset.java:99)
	at com.vividsolutions.jump.workbench.imagery.ReferencedImageStyle.paint(ReferencedImageStyle.java:54)
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleFeatureCollectionRenderer.paint(SimpleFeatureCollectionRenderer.java:44)
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleFeatureCollectionRenderer.paint(SimpleFeatureCollectionRenderer.java:62)
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleRenderer.copyTo(SimpleRenderer.java:74)
	at com.vividsolutions.jump.workbench.ui.renderer.FeatureCollectionRenderer.copyTo(FeatureCollectionRenderer.java:55)
	at com.vividsolutions.jump.workbench.ui.renderer.LayerRenderer.copyTo(LayerRenderer.java:93)
	at com.vividsolutions.jump.workbench.ui.renderer.RenderingManager.copyTo(RenderingManager.java:362)
	at com.vividsolutions.jump.workbench.ui.LayerViewPanel.paintComponent(LayerViewPanel.java:548)

**Comment by edeso** [comment]
@mukoki should be fixed, can you check?

**Comment by mukoki** [comment]
Yes, fixed for me. Thank you !
