### ISSUE TITLE
Draw linestring tool unusable

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#38]
Probably a regression related to "Contextualize CursorTool ..." commited on 20/06/2021

How to reproduce the error : open the Editing ToolBox just after application has started. Select the Draw LineString tool 

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.vividsolutions.jump.workbench.ui.cursortool.AbstractCursorTool.getWorkbenchFrame(AbstractCursorTool.java:603)
        at com.vividsolutions.jump.workbench.ui.cursortool.MultiClickTool.deactivate(MultiClickTool.java:261)
        at com.vividsolutions.jump.workbench.ui.cursortool.DelegatingTool.deactivate(DelegatingTool.java:101)
        at com.vividsolutions.jump.workbench.ui.cursortool.DelegatingTool.deactivate(DelegatingTool.java:101)
        at com.vividsolutions.jump.workbench.ui.cursortool.QuasimodeTool.setTool(QuasimodeTool.java:297)
        at com.vividsolutions.jump.workbench.ui.cursortool.QuasimodeTool.revalidateQuasiMode(QuasimodeTool.java:261)
        at com.vividsolutions.jump.workbench.ui.cursortool.QuasimodeTool.activate(QuasimodeTool.java:313)
        at com.vividsolutions.jump.workbench.ui.LayerViewPanel.setCurrentCursorTool(LayerViewPanel.java:396)
        at com.vividsolutions.jump.workbench.ui.LayerViewPanel.setCurrentCursorTool(LayerViewPanel.java:379)

**Comment by edeso** [comment]
@mukoki should be fixed. reopen if needed.
