### ISSUE TITLE
Missing super.initialize()

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#39]
Selecting all features with Ctrl-A throws

Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Add super.initialize() to your AbstractPlugIn.initialize() implementation!
org.openjump.core.ui.plugin.edit.SelectAllLayerItemsPlugIn
	at com.vividsolutions.jump.workbench.plugin.AbstractPlugIn.getContext(AbstractPlugIn.java:412)
	at com.vividsolutions.jump.workbench.plugin.AbstractPlugIn.getEnableCheck(AbstractPlugIn.java:233)
	at com.vividsolutions.jump.workbench.ui.ShortcutPluginExecuteKeyListener.keyPressed(ShortcutPluginExecuteKeyListener.java:97)

**Comment by edeso** [comment]
just looking at it and find we have lot's of Core plugins not promoting the context, will provide a patchset for all i can find
