### ISSUE TITLE
Error Saving project

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#41]
"**Saving project**" or "**Saving project as**" in the File menu sometimes throws the following error.
Seems related to the fact that one of the layer has been saved using "**Save dataset as (testing)**" command.

com.vividsolutions.jump.util.java2xml.XMLBinder$XMLBinderException: Could not find java2xml file for java.net.URI or its interfaces or superclasses
	at com.vividsolutions.jump.util.java2xml.XMLBinder.specElements(XMLBinder.java:330)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:181)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:172)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTags(Java2XML.java:202)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$100(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:102)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:181)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTags(Java2XML.java:202)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$100(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:102)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:181)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTags(Java2XML.java:202)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$100(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:102)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:181)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTags(Java2XML.java:199)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$100(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:102)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTag(Java2XML.java:181)
	at com.vividsolutions.jump.util.java2xml.Java2XML.writeChildTags(Java2XML.java:199)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$100(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:102)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.access$200(Java2XML.java:55)
	at com.vividsolutions.jump.util.java2xml.Java2XML$1.tagSpecFound(Java2XML.java:114)
	at com.vividsolutions.jump.util.java2xml.XMLBinder.visit(XMLBinder.java:389)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:97)
	at com.vividsolutions.jump.util.java2xml.Java2XML.write(Java2XML.java:80)
	at com.vividsolutions.jump.workbench.ui.plugin.AbstractSaveProjectPlugIn.save(AbstractSaveProjectPlugIn.java:105)
	at com.vividsolutions.jump.workbench.ui.plugin.SaveProjectAsPlugIn.execute(SaveProjectAsPlugIn.java:128)
	at com.vividsolutions.jump.workbench.ui.plugin.SaveProjectPlugIn.execute(SaveProjectPlugIn.java:63)
	at com.vividsolutions.jump.workbench.plugin.AbstractPlugIn$1.actionPerformed(AbstractPlugIn.java:341)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by chrisdebian** [comment]
Confirmed and root-caused, verified against current `main` (source-level check only — no Maven/display available in my environment).

`DataSourceFileLayerSaver.write()` — used specifically by File > Save dataset as (testing), not the regular Save dataset as — stores the raw `java.net.URI` object directly as a DataSource parameter:

```java
options.put(DataSource.URI_KEY, uri);
```
(`DataSourceFileLayerSaver.java:51`)

There's no `java2xml` binding registered anywhere in the codebase for `java.net.URI` (searched for a `URI.java2xml` spec file — none exists). When the project is subsequently saved, this parameter gets serialized along with the rest of the layer's DataSourceQuery, and a `URI` with no binding throws exactly the reported exception. This matches the report precisely: only layers saved via the "(testing)" wizard carry this parameter, so only those trigger the failure on the next project save.

A fix would need either a `URI.java2xml` binding, or storing the value as a `String`/`File` (as the regular save path already does) instead of a raw `URI`. I haven't attempted a fix here, just the root-cause confirmation.

**Comment by chrisdebian** [comment]
Update: I now have Maven available and the project builds cleanly (`mvn -B package -P snapshot`, `BUILD SUCCESS`), with all 147 existing tests passing. Confirms the file/line I quoted above is real, compiling code — not a misread. Still no display available to interactively test the UI behaviour itself.
