### ISSUE TITLE
Exception thrown at OpenJUMP start

### ISSUE THREAD

**Issue by mukoki** [openjump-gis/openjump#54]
While opening OpenJUMP PLUS (OpenJUMP-Portable-20220620-r5116), the following exception is thrown (maybe related to https://github.com/openjump-gis/openjump/issues/53)

 (java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider it.geosolutions.imageio.plugins.arcbinarygrid.ArcBinaryGridImageReaderSpi could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at java.desktop/javax.imageio.spi.IIORegistry.registerApplicationClasspathSpis(IIORegistry.java:188)
	at java.desktop/javax.imageio.spi.IIORegistry.<init>(IIORegistry.java:113)
	at java.desktop/javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:134)
	at java.desktop/javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at com.cadplan.fill_patterns.jump.LoadFillPatterns.loadImageIO(LoadFillPatterns.java:192)
	at com.cadplan.fill_patterns.jump.LoadFillPatterns.loadNames(LoadFillPatterns.java:182)
	at com.cadplan.fill_patterns.jump.LoadFillPatterns.<init>(LoadFillPatterns.java:72)
	at com.cadplan.fill_patterns.jump.FillPatternsPlugIn.initialize(FillPatternsPlugIn.java:56)
	at com.cadplan.fill_patterns.jump.FillPatternsExtension.configure(FillPatternsExtension.java:45)
	at com.vividsolutions.jump.workbench.plugin.PlugInManager.loadConfigurations(PlugInManager.java:258)
	at com.vividsolutions.jump.workbench.plugin.PlugInManager.load(PlugInManager.java:237)
	at com.vividsolutions.jump.workbench.JUMPWorkbench.main(JUMPWorkbench.java:461)
	at com.vividsolutions.jump.workbench.JUMPWorkbench.main(JUMPWorkbench.java:396)
Caused by: java.lang.NoClassDefFoundError: org/gdal/gdal/gdal
	at it.geosolutions.imageio.gdalframework.GDALUtilities.loadGDAL(GDALUtilities.java:674)
	at it.geosolutions.imageio.gdalframework.GDALImageReaderSpi.<clinit>(GDALImageReaderSpi.java:56)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 15 more
)

**Comment by edeso** [comment]
my bad, "optimized" size by excluding `gdal.jar` bindings packaging. will add them back.

**Comment by edeso** [comment]
should be fixed with https://github.com/openjump-gis/openjump/commit/dcbe0b5add54f07660dc087df0c1db3c48abfb24
