### ISSUE TITLE
CADTools - Drawing Blocks throws NPEs 

### ISSUE THREAD

**Issue by ma15569** [openjump-gis/openjump#56]
PlugIn: CADTools

Bug description: It is not possible to draw a good 50% of the embedded blocks this which throw null point exceptions.

It seems that blocks made by simple polygons or multipolygons with no holes can be drawn.
Blocks made by the previous geometries with holes not.

Blocks displayed by CADTools are stored into Lib/Ext/VertexImages folder (blocks are used by CadPlan Vertex Images plugin too) and they are simple WKT files

**Comment by ma15569** [comment]
OpenJUMP-Portable-20220823-r5135[6899249]-PLUS

Just a reminder to explain the bug and define the last test

**CadTools:** the bug affects blocks made by polygons with holes (for instance bore_01 or geology_05. It does not ot affect blocks made by polygons without holes (for instance geology_01) or multipolygons (geology_03)

**Vertex Synbology** the same:  the bug affects shapes (symbols) made by polygons with holes (for instance bore_01 or geology_05. It does not ot affect blocks made by polygons without holes (for instance geology_01) or multipolygons (geology_03)

Both CadTools and Vertex Synbology define the geometries/shapes reading  WKT files in lib/ext/VertexImages folder

**Comment by edeso** [comment]
Peppe,

let me refer you to my answers on the sf.net ticket, 
https://sourceforge.net/p/jump-pilot/bugs/522/#1cb9

also i explicitly asked you **not** to open another one here, guess you didn't see that.

so again, works for me since rev5128 see ![bore01](https://user-images.githubusercontent.com/9976129/186492556-19e628a6-31b1-46b2-bd7d-35c5b1cb5fd4.JPG)


if it still does not for you i will need more details. specifically 
- the error stack from the log and 
- maybe the java runtime you use
as i'm not able to replicate any issue.

i will close the issue an sf.net assuming that we will stay here the for the issue being.

**Comment by ma15569** [comment]
Hi Ede,
At this point I am considering it is a problem of the Java version I have

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 1.8.0_311-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.311-b11, mixed mode)

This is  the error stack from the log fileç

 (Null Pointer Exception)
[ERROR] 2022-08-25_06:56:04.390 java.lang.NullPointerException
java.lang.NullPointerException
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleFeatureCollectionRenderer.paint(SimpleFeatureCollectionRenderer.java:27)
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleFeatureCollectionRenderer.paint(SimpleFeatureCollectionRenderer.java:58)
	at com.vividsolutions.jump.workbench.ui.renderer.SimpleRenderer.copyTo(SimpleRenderer.java:74)
	at com.vividsolutions.jump.workbench.ui.renderer.FeatureCollectionRenderer.copyTo(FeatureCollectionRenderer.java:55)
	at com.vividsolutions.jump.workbench.ui.renderer.LayerRenderer.copyTo(LayerRenderer.java:93)
	at com.vividsolutions.jump.workbench.ui.renderer.RenderingManager.copyTo(RenderingManager.java:362)
	at com.vividsolutions.jump.workbench.ui.LayerViewPanel.paintComponent(LayerViewPanel.java:486)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
[INFO] 2022-08-25_06:56:04.392 Avvertimento: Descrizione non disponibile

**Comment by ma15569** [comment]
The same bug with the latest java version "1.8.0_341"

**Comment by ma15569** [comment]
The previous  error message is  probabily connected to Vertex Images plugin.
It cames out when I try to open a project with ExtendedVertexSymbols in it


The following error pops out  when I try to draw a block with CadTools
java.lang.NullPointerException
	at com.vividsolutions.jump.workbench.plugin.AbstractPlugIn.execute(AbstractPlugIn.java:376)
	at com.vividsolutions.jump.workbench.ui.cursortool.AbstractCursorTool.execute(AbstractCursorTool.java:640)
	at org.openjump.advancedtools.block.DrawOrientedBlockTool.gestureFinished(DrawOrientedBlockTool.java:121)
	at com.vividsolutions.jump.workbench.ui.cursortool.AbstractCursorTool.fireGestureFinished(AbstractCursorTool.java:621)
	at org.openjump.core.ui.plugin.edittoolbox.cursortools.ConstrainedMultiClickTool.finishGesture(ConstrainedMultiClickTool.java:280)
	at org.openjump.core.ui.plugin.edittoolbox.cursortools.ConstrainedMultiClickTool.mouseReleased(ConstrainedMultiClickTool.java:155)
	at com.vividsolutions.jump.workbench.ui.cursortool.DelegatingTool.mouseReleased(DelegatingTool.java:105)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ma15569** [comment]
I Ede, 
this is a description of the bug with java version "1.8.0_341" with **CadTools**

a) select the first icon to the left (Draw a block), select block bore_01
 Everything is fine and the block is drawn with no errors

b) select the second icon to the left (Draw an oriented block)
- move the cursor on the workbench: the shade of the block appears following the cursor, no error
- one click and move the cursor: the shade stays on the click coorsinates rotating according the position of the cursor, no error
- Dragging the cursor with second click: angle of rotation comes out on the status bar, rotates, no error
- Second click )which should draw the rotated block), **the error pops up**

_```
java.lang.NullPointerException
at com.vividsolutions.jump.workbench.plugin.AbstractPlugIn.execute(AbstractPlugIn.java:376)
at com.vividsolutions.jump.workbench.ui.cursortool.AbstractCursorTool.execute(AbstractCursorTool.java:640)
at org.openjump.advancedtools.block.DrawOrientedBlockTool.gestureFinished(DrawOrientedBlockTool.java:121)
at com.vividsolutions.jump.workbench.ui.cursortool.AbstractCursorTool.fireGestureFinished(AbstractCursorTool.java:621)
at org.openjump.core.ui.plugin.edittoolbox.cursortools.ConstrainedMultiClickTool.finishGesture(ConstrainedMultiClickTool.java:280)
at org.openjump.core.ui.plugin.edittoolbox.cursortools.ConstrainedMultiClickTool.mouseReleased(ConstrainedMultiClickTool.java:155)
at com.vividsolutions.jump.workbench.ui.cursortool.DelegatingTool.mouseReleased(DelegatingTool.java:105)
...
```_

With the previous java version 1.8.0_311 both  a) and b) were generating errors

With OpenJUMP 1.16 no error were generating (I did this test just in case to have an history if there wers some changes)

I still think that the bug in CadTools and the one in VertexImagesas are related as they share some code on how to read WKT symbols, **rotate** and transform into geometries. I will not open another issue, maybe solving CadTools solves also VertexImage

Bets regards

**Comment by edeso** [comment]
> a) select the first icon to the left (Draw a block), select block bore_01 _Everything is fine and the block is drawn with no errors_ as in picture of your message

yes, this was fixed in my initial approach
 
> b) select the second icon to the left (Draw an oriented block)
SNIP

right, didn't try that one. the fix is identical and i'll tackle that soonish

> Note that, with the older java version **1.8.0_311**, both a) and b) _were generating errors_
> 
> With OpenJUMP 1.16 no error were generating (I did this test just in case to have an history if there wers some changes)

according to my debugging the cause lies in the upgraded jts 1.19 . for some reason some symbols fail the geometry validity test. as they are only symbols, deactivatiing the need for validity solves the issue.

> I still think that the bug in **CadTools** and the one in **VertexImagesas** are related as they share some code on how to read WKT symbols, _**rotate**_ and transform into geometries. I will not open another issue, maybe solving CadTools solves also VertexImage

wrt. VertexSymbols. please **try to create a new project with VertexSymbol decorations in OJ2**. we lost old OJ1.x project compatibility as it seems in that regard.

**Comment by edeso** [comment]
hey @ma15569 

pls test the next snapshot. the issue should be fixed now. if so pls close this issue . thx!

**Comment by ma15569** [comment]
The bug is solved for CADTools Blocks plugin.
I  close this issue
